# Site settings
title: 读万卷书，行万里
email: gaiyangjun@hotmail.com
description: 个人读书笔记
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: gaiyangjun
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/gaiyangjun/gaiyangjun.github.io/blob/master/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/gaiyangjun/gaiyangjun.github.io/new/master
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: gaiyangjun
#duoshuo_url: "http://gaiyangjun.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: gaiyangjun
disqus_url: "http://gaiyangjun.github.io"
#########################################

# Build settings
# google_analytics: UA-105221129-1
markdown: kramdown
highlighter: rouge
# highlighter: false

github: gaiyangjun
kramdown:
   input: GFM
   hard_wrap: false

theme: jekyll-theme-cayman